# vim: set ft=yaml.ansible:
---
- hosts: all
  become: yes
  vars_files:
    - ../vars/main.yaml
  pre_tasks:
    - name: Update apt cache once before installing all the packages
      apt:
        update_cache: yes
  roles:
    - geerlingguy.github-users
    - geerlingguy.ntp
    - geerlingguy.security
    - geerlingguy.docker
